1701A:
  aliases: []
  note: on-site
  x: -17.155
  y: 2.891
  yaw: 170.6
1701B门口:
  aliases: []
  note: on-site
  x: -7.186
  y: 0.903
  yaw: 171.1
1705门口:
  aliases: []
  note: on-site
  x: 7.813
  y: 2.779
  yaw: 0.4
1706门口:
  aliases: []
  note: on-site
  x: 7.031
  y: -1.377
  yaw: 0.8
1707门口:
  aliases: []
  note: on-site
  x: 6.504
  y: -2.769
  yaw: -8.7
1708门口:
  aliases: []
  note: on-site
  x: 5.455
  y: -7.2
  yaw: -13.9
1709门口:
  aliases: []
  note: on-site
  x: 5.192
  y: -9.844
  yaw: -97.8
1710门口:
  aliases: []
  note: on-site
  x: 4.04
  y: -13.899
  yaw: -104.1
1716A门口:
  aliases: []
  note: on-site
  x: -8.773
  y: -17.79
  yaw: 80.6
1716B门口:
  aliases: []
  note: on-site
  x: -16.219
  y: -16.409
  yaw: -12.1
1717A门口:
  aliases: []
  note: on-site
  x: -18.101
  y: -16.189
  yaw: -10.1
1717B门口:
  aliases: []
  note: on-site
  x: -22.887
  y: -14.856
  yaw: -101.5
1718A门口:
  aliases: []
  note: on-site
  x: -22.643
  y: -12.345
  yaw: -100.7
1718B门口:
  aliases: []
  note: on-site
  x: -19.719
  y: 0.998
  yaw: -99.2
